defaults:
  - input: cifar10
  - model: ${input}
  - training: ${input}
  - hydra: defaults
  - wandb: defaults
  - _self_

seed: 42
device: "cuda"

input:
  batch_size: 100

model:
  goodness_type: sum
  theta: 2.0  # 当 goodness_type 为 sum 时, 不用管 theta.

  peer_normalization: 0.0 # modif dqr: 将 peer_norm 置为0, 观察效果.
  embed_dim: 256
  hidden_dim: 512
  num_heads: 8
  num_layers: 6
  patch_size: 4
  num_channels: 3
  num_patches: 64
  num_classes: 10
  dropout: 0.2
  
training:
  # test_mode: compute_each_label
  test_mode: one_pass_softmax

  final_test: True

  epochs: 200
  learning_rate: 1e-4 # modif 1: 减少 lr, 缓解 dead relu
  lr_boundary_points: [[100, 1e-4], 1e-5]

  # 当 test_mode 为 "compute_each_label" 时, 
  # 不用管下面三行 downstream 开头的参数;
  downstream_learning_rate: 1e-2
  downstream_weight_decay: 3e-6 # modif 4: 把 cls_layer 的 weight_decay 设置成与 ff_layer 一样小, 先追求 overfitting.
  downstream_lr_boundary_points: [[100, 1e-2], 0.3e-2]



